### PR TITLE
Support new version of LazySets

### LINKED ISSUE #211: install issue
I should first mention that I have used this package previously (before February 2023) with no issues. Recently I am encountering an install issue related to LazySets. I am running julia 1.8.0 and I am installing on the same system I used before. The installation prompts the following message:
 

> Installed MathOptInterface ──────────── v1.13.1
  Downloaded artifact: PicoSAT
  Downloaded artifact: GLPK
  Downloaded artifact: Bzip2
  Downloaded artifact: SCS_GPU
  Downloaded artifact: EarCut
  Downloaded artifact: cddlib
  Downloaded artifact: SCS_MKL
  Downloaded artifact: OpenBLAS32
  Downloaded artifact: IntelOpenMP
  Downloaded artifact: SCS
  Downloaded artifact: OpenSpecFun
  Downloaded artifact: CRlibm
    Updating `~/.julia/environments/v1.8/Project.toml`
  [146f25fa] + NeuralVerification v0.1.0 `https://github.com/sisl/NeuralVerification.jl#master`
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [79e6a3ab] + Adapt v3.6.1
  [13072b0f] + AxisAlgorithms v1.0.1
  [6e4b80f9] + BenchmarkTools v1.3.2
  [3391f64e] + CDDLib v0.9.1
  [96374032] + CRlibm v1.0.1
  [d360d2e6] + ChainRulesCore v1.15.7
  [9e997f8a] + ChangesOfVariables v0.1.6
  [523fee87] + CodecBzip2 v0.7.2
  [944b1d66] + CodecZlib v0.7.1
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.6.1
  [9a962f9c] + DataAPI v1.14.0
  [864edb3b] + DataStructures v0.18.13
  [e2d170a0] + DataValueInterfaces v1.0.0
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.13.0
  [ffbed154] + DocStringExtensions v0.9.3
  [90fa49ef] + ErrorfreeArithmetic v0.5.2
  [e2ba6199] + ExprTools v0.1.8
  [411431e0] + Extents v0.1.1
  [fa42c844] + FastRounding v0.3.1
  [f6369f11] + ForwardDiff v0.10.35
  [60bf3e95] + GLPK v1.1.1
  [46192b85] + GPUArraysCore v0.1.4
  [14197337] + GenericLinearAlgebra v0.3.7
  [cf35fbd7] + GeoInterface v1.2.1
  [5c1252a2] + GeometryBasics v0.4.5
  [a98d9a8b] + Interpolations v0.14.7
  [d1acc4aa] + IntervalArithmetic v0.20.8
  [3587e190] + InverseFunctions v0.1.8
  [92d709cd] + IrrationalConstants v0.2.2
  [c8e1da08] + IterTools v1.4.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [4076af6c] + JuMP v1.9.0
⌃ [b4f0291d] + LazySets v1.59.1
  [2ab3a3ac] + LogExpFunctions v0.3.23
  [b8f27783] + MathOptInterface v1.13.1
  [d8a4904e] + MutableArithmetics v1.2.3
  [77ba4419] + NaNMath v1.0.2
  [146f25fa] + NeuralVerification v0.1.0 `https://github.com/sisl/NeuralVerification.jl#master`
  [6fe1bfb0] + OffsetArrays v1.12.9
  [bac558e1] + OrderedCollections v1.4.1
  [d96e819e] + Parameters v0.12.3
  [ff2beb65] + PicoSAT v0.4.0
  [67491407] + Polyhedra v0.7.6
  [c84ed2f1] + Ratios v0.4.3
  [3cdcf5f2] + RecipesBase v1.3.3
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
  [5eaf0fd0] + RoundingEmulator v0.2.1
  [c946c3f1] + SCS v1.1.3
  [3cc68bcd] + SetRounding v0.2.1
  [276daf66] + SpecialFunctions v2.2.0
  [90137ffa] + StaticArrays v1.5.16
  [1e83bf80] + StaticArraysCore v1.4.0
  [09ab397b] + StructArrays v0.6.14
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.10.0
  [3bb67fe8] + TranscodingStreams v0.9.11
  [3a884ed6] + UnPack v1.0.2
  [efce3f68] + WoodburyMatrices v0.5.5
  [6e34b625] + Bzip2_jll v1.0.8+0
  [4e9b3aee] + CRlibm_jll v1.0.1+0
  [5ae413db] + EarCut_jll v2.2.4+0
  [e8aa6df9] + GLPK_jll v5.0.1+0
  [1d5cc7b8] + IntelOpenMP_jll v2018.0.3+2
  [856f044c] + MKL_jll v2022.2.0+0
⌅ [656ef2d0] + OpenBLAS32_jll v0.3.17+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [e78fa76d] + PicoSAT_jll v965.0.0+0
  [af6e375f] + SCS_GPU_jll v3.2.1+0
  [3f2553a9] + SCS_MKL_jll v3.2.2+0
  [f4f2fc5b] + SCS_jll v3.2.1+0
  [f07e07eb] + cddlib_jll v0.94.13+0
  [8ba89e20] + Distributed
  [4af54fe1] + LazyArtifacts
  [9abbd945] + Profile
  [1a1011a3] + SharedArrays
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [781609d7] + GMP_jll v6.2.1+2
  [05823500] + OpenLibm_jll v0.8.1+0
        Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ cannot be upgraded. To see why use `status --outdated -m`
Precompiling project...
  ✗ LazySets
  ✗ NeuralVerification
  74 dependencies successfully precompiled in 61 seconds. 21 already precompiled.
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

Calling the library afterwards produces the following error:

>using NeuralVerification
[ Info: Precompiling NeuralVerification [146f25fa-00e7-11e9-3ae5-fdbac6e12fa7]
ERROR: LoadError: UndefVarError: MathOptInterface not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [2] include(x::String)
   @ LazySets ~/.julia/packages/LazySets/HlinV/src/LazySets.jl:4
 [3] top-level scope
   @ ~/.julia/packages/LazySets/HlinV/src/LazySets.jl:35
 [4] include
   @ ./Base.jl:419 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [6] top-level scope
   @ stdin:1
in expression starting at /root/.julia/packages/LazySets/HlinV/src/Initialization/init_JuMP.jl:1
in expression starting at /root/.julia/packages/LazySets/HlinV/src/LazySets.jl:4
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043] to /root/.julia/compiled/v1.8/LazySets/jl_7ZERhS.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1705
  [3] compilecache
    @ ./loading.jl:1649 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /root/.julia/packages/NeuralVerification/rq2QM/src/NeuralVerification.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile NeuralVerification [146f25fa-00e7-11e9-3ae5-fdbac6e12fa7] to /root/.julia/compiled/v1.8/NeuralVerification/jl_rsoKtS.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1705
 [3] compilecache
   @ ./loading.jl:1649 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144

### LINKED ISSUE #213: Ai2h and VPolytope construction
If I update to the latest version of LazySets (v2.11), or even some older versions, then I get this error when running the tests:
```
Group 1: Error During Test at C:\Users\mykel\.julia\dev\NeuralVerification\test\identity_network.jl:17
  Got exception outside of a @test
  MethodError: no method matching VPolytope(::VPolygon{Float64, Vector{Float64}})

  Closest candidates are:
    VPolytope()
     @ LazySets C:\Users\mykel\.julia\packages\LazySets\GNSCF\src\Sets\VPolytope.jl:66
    VPolytope(::Polyhedra.VRep{N}) where N
     @ LazySets C:\Users\mykel\.julia\packages\LazySets\GNSCF\src\Sets\VPolytope.jl:553
    VPolytope(::VT) where {N, VN<:AbstractVector{N}, VT<:AbstractVector{VN}}
     @ LazySets C:\Users\mykel\.julia\packages\LazySets\GNSCF\src\Sets\VPolytope.jl:57
    ...

  Stacktrace:
    [1] convex_hull(U::UnionSetArray{Float64, HPolytope{Float64, VN} where VN<:AbstractVector{Float64}})
      @ NeuralVerification C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\ai2.jl:76
    [2] forward_act(solver::Ai2h, L::NeuralVerification.Layer{ReLU, Float64}, Ẑ::HPolytope{Float64, Vector{Float64}})
      @ NeuralVerification C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\ai2.jl:67
    [3] forward_layer(solver::Ai2h, layer::NeuralVerification.Layer{ReLU, Float64}, reach::HPolytope{Float64, ReachabilityBase.Arrays.SingleEntryVector{Float64}})
      @ NeuralVerification C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\utils\reachability.jl:59
    [4] _forward_network(solver::Ai2h, nnet::Network, input::HPolytope{Float64, ReachabilityBase.Arrays.SingleEntryVector{Float64}})
      @ NeuralVerification C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\utils\reachability.jl:26
    [5] #forward_network#78
      @ C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\utils\reachability.jl:18 [inlined]
    [6] forward_network
      @ C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\utils\reachability.jl:10 [inlined]
    [7] solve(solver::Ai2h, problem::Problem{HPolytope{Float64, ReachabilityBase.Arrays.SingleEntryVector{Float64}}, HPolytope{Float64, ReachabilityBase.Arrays.SingleEntryVector{Float64}}})
      @ NeuralVerification C:\Users\mykel\.julia\dev\NeuralVerification\src\reachability\ai2.jl:54
    [8] macro expansion
      @ C:\Users\mykel\.julia\dev\NeuralVerification\test\identity_network.jl:22 [inlined]
    [9] macro expansion
      @ C:\Users\mykel\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Test\src\Test.jl:1577 [inlined]
   [10] macro expansion
      @ C:\Users\mykel\.julia\dev\NeuralVerification\test\identity_network.jl:18 [inlined]
   [11] macro expansion
      @ C:\Users\mykel\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Test\src\Test.jl:1577 [inlined]
   [12] top-level scope
      @ C:\Users\mykel\.julia\dev\NeuralVerification\test\identity_network.jl:4
   [13] include(fname::String)
      @ Base.MainInclude .\client.jl:489
   [14] top-level scope
      @ C:\Users\mykel\.julia\dev\NeuralVerification\test\runtests.jl:19
   [15] include(fname::String)
      @ Base.MainInclude .\client.jl:489
   [16] top-level scope
      @ none:6
   [17] eval
      @ Core .\boot.jl:385 [inlined]
   [18] exec_options(opts::Base.JLOptions)
      @ Base .\client.jl:291
   [19] _start()
      @ Base .\client.jl:552
```
The issue is with Ai2h. The other solvers seem to work just fine. It is failing on this call: `tohrep(VPolytope(LazySets.convex_hull(U)))`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #211.
Closes #213.

### CODE REVIEW

**Comment by mykelk** [comment]
Thanks! I merged because it looks like the tests were passing on this PR, but it looks like after the merge we have this:

image

**Comment by schillic** [comment]
To me this is not concerning. I believe this just means that some LP problem is numerically tricky. We have seen such warnings in `LazySets` for years, also in some of the unit tests. In principle we just pass on the constraints from the user to the LP solver, so it is less likely that there is something wrong on our end. The results are still correct since the tests pass.

**Comment by mykelk** [comment]
Ah okay... I saw the two broken tests listed there. Shall we tag a 0.1.1 release then?

**Comment by schillic** [comment]
Ah, you meant those. They were broken before. I did not touch the tests.
I leave the tagging decision to you :+1:

**Pull request merged**
