### PR TITLE
Dev tests

### PR DESCRIPTION
**Pull request by tomerarnon**
Fix ai2, and add it to the tests. Should address #36.

### CODE REVIEW

**Comment by tomerarnon** [comment]
> We should support 1.1.

In this case it's really up to the Polyhedra authors. I'll open an issue.

**Comment by chelseas** [comment]
I'm the author of #36 . Is there something I can do to get this working with Julia 1.0 in the meantime while we wait for the authors of Polyhedra to do something?

**Comment by mykelk** [comment]
This currently works for 1.0. I'm fine with merging. For Travis, we can allow failures for 1.1 for now, so just update .travis.yml.

**Comment by tomerarnon** [comment]
@chelseas I'll merge this as soon as the tests pass. Check back in a half hour!

**Comment by chelseas** [comment]
Wait I've been using Julia1.0 the whole time and I'm still getting this failure. your tests are missing something if they pass.

**Pull request merged**
